env: LunarLander-v2
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 1000
nbTest: 100
freqVerbose: 1000
fromFile: null
nbEpisodes: 1000000
freqOptim: 1000
freqPrint: 10